# Generated by Django 5.0.6 on 2024-07-01 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cves", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cve",
            name="name",
        ),
    ]
